
"use client";
import { useLanguage } from "@/components/language-provider";

export function SEOContent() {
  const { lang } = useLanguage();
  
  if (lang === "FI") {
    return (
      <div className="prose prose-sm md:prose-base dark:prose-invert max-w-none mt-20 pt-10 border-t border-border/50 text-muted-foreground">
        <p className="mb-4">Ammattilaistason ajanotto on urheilutapahtumien sydän. Eqilo Oy on omistautunut tuomaan maailmanluokan FDS Timing -laitteet suomalaisten urheiluseurojen ja tapahtumajärjestäjien saataville. Olemme erikoistuneet erityisesti ratsastuksen ja agilityn ajanottoratkaisuihin, joissa vaaditaan äärimmäistä tarkkuutta ja luotettavuutta. Kun puhutaan sadasosasekuntien eroista, ei ole varaa kompromisseihin. FDS Timing -laitteet, jotka on suunniteltu ja valmistettu Sveitsissä, edustavat alan huippua ja tarjoavat pettämättömän suorituskyvyn kaikissa olosuhteissa.</p>
        <p className="mb-4">Ratsastuskilpailuissa, kuten esteratsastuksessa ja kouluratsastuksessa, ajanoton on oltava paitsi tarkkaa myös saumattomasti integroitavissa tulospalvelujärjestelmiin. Equipe APP on muodostunut alan standardiksi, ja laitteidemme täysi yhteensopivuus tämän järjestelmän kanssa takaa kilpailun sujuvan läpiviennin. Langattomat valokennot, suuret ja selkeät LED-näyttötaulut sekä varmatoimiset langattomat lähettimet tekevät radan rakentamisesta nopeaa ja tulosten esittämisestä yleisöystävällistä. Eqilo Oy tarjoaa kaiken tarvittavan laitteiston aina pienistä seurakilpailuista suuriin kansainvälisiin tapahtumiin.</p>
        <p className="mb-4">Agilityssä koirien nopeus ja radan monimutkaisuus asettavat ajanottolaitteistolle omat haasteensa. FDS Timingin innovatiiviset ratkaisut, kuten erittäin nopeat ja säänkestävät valokennot, takaavat, että jokainen suoritus mitataan millisekuntien tarkkuudella. Lisäksi laitteistomme on suunniteltu kestämään Suomen vaativia sääolosuhteita, aina paahtavasta auringonpaisteesta rankkasateisiin. Tämä tekee niistä ihanteellisen valinnan myös ulkokentillä järjestettäviin kilpailuihin.</p>
        <p className="mb-4">Me Eqilo Oy:ssä ymmärrämme, että laitteiden hankinta on seuroille merkittävä investointi. Siksi emme ole vain laitetoimittaja, vaan kumppani. Tarjoamme kattavaa asiantuntijapalvelua, joka auttaa seuroja valitsemaan juuri heidän tarpeisiinsa ja budjettiinsa sopivimman kokonaisuuden. Pitkän aikavälin tavoitteenamme on alentaa kynnystä ammattimaisen ajanottoteknologian käyttöönottoon Suomessa. FDS Timing -järjestelmien modulaarisuus mahdollistaa sen, että laitteistoa voi laajentaa seuran tarpeiden ja resurssien kasvaessa.</p>
        <p className="mb-4">Hankinnan lisäksi Eqilo Oy painottaa koulutuksen ja tuen tärkeyttä. Paraskaan laitteisto ei palvele tarkoitustaan, jos sen käyttäjät eivät osaa hyödyntää sen kaikkia ominaisuuksia. Tarjoamme räätälöityjä koulutuksia niin laitteiden fyysiseen pystytykseen kuin ohjelmistojen, kuten Equipe APP:n, käyttöön. Asiantuntijamme ovat myös tavoitettavissa kilpailuviikonloppuina mahdollisten teknisten ongelmien varalta, varmistaen, että tapahtumat viedään läpi kunnialla.</p>
        <p className="mb-4">Sveitsiläinen insinööritaito, joka on synonyymi tarkkuudelle ja laadulle, on vahvasti läsnä jokaisessa FDS Timing -tuotteessa. Laitteiden kestävyys, pitkä akkukesto ja intuitiivinen käyttöliittymä tekevät niistä luotettavan työkalun vuodesta toiseen. Olemme ylpeitä voidessamme toimia FDS Timingin virallisena edustajana Suomessa ja tuoda nämä innovaatiot paikallisten urheilijoiden ja järjestäjien ulottuville.</p>
        <p className="mb-4">Olipa kyseessä sitten uuden ajanottojärjestelmän hankinta, vanhan päivittäminen tai laitteiston vuokraus yksittäiseen tapahtumaan, Eqilo Oy on valmiina palvelemaan. Kokoamme jatkuvasti palautetta kentältä ja kehitämme palveluitamme vastataksemme entistä paremmin suomalaisen urheilukentän tarpeisiin. Tutustu valikoimaamme verkkokaupassamme, tai ota yhteyttä asiantuntijoihimme henkilökohtaisen tarjouksen saamiseksi.</p>
        <p className="mb-4">Urheilun digitalisoituessa myös tulospalvelun odotukset kasvavat. Reaaliaikaiset tulokset verkossa ja paikan päällä olevilla näytöillä eivät ole enää luksusta, vaan perusvaatimus. Eqilo Oy:n tarjoamat ratkaisut mahdollistavat saumattoman tiedonsiirron radalta tulospalveluun ja sieltä suoraan yleisölle. Tämä ei ainoastaan paranna kilpailijoiden ja katsojien kokemusta, vaan tekee myös järjestäjien työstä huomattavasti tehokkaampaa.</p>
        <p className="mb-4">Olemme myös tietoisia ympäristövastuustamme. FDS Timing -laitteet on suunniteltu pitkäikäisiksi, ja niiden modulaarinen rakenne mahdollistaa yksittäisten osien korjaamisen ja päivittämisen koko järjestelmän uusimisen sijaan. Tämä vähentää elektronista jätettä ja tarjoaa seuroille kestävän ja kustannustehokkaan vaihtoehdon.</p>
        <p className="mb-4">Eqilo Oy:n tarina alkoi intohimosta urheiluun ja teknologiin. Haluamme olla mukana kehittämässä suomalaista urheilukulttuuria tarjoamalla työkalut, jotka mahdollistavat entistä tasapuolisemmat ja ammattimaisemmat kilpailut. Ota askel kohti parempaa ajanottoa ja valitse Eqilo Oy kumppaniksesi.</p>
      </div>
    );
  }
  
  if (lang === "SE") {
    return (
      <div className="prose prose-sm md:prose-base dark:prose-invert max-w-none mt-20 pt-10 border-t border-border/50 text-muted-foreground">
        <p className="mb-4">Tidtagning på professionell nivå är hjärtat i idrottsevenemang. Eqilo Oy är dedikerade till att erbjuda världsklassig FDS Timing-utrustning till idrottsklubbar och evenemangsorganisatörer i Finland. Vi specialiserar oss särskilt på tidtagningslösningar för ridsport och agility, där extrem precision och absolut tillförlitlighet krävs. När millisekunder avgör vinnaren finns det inget utrymme för kompromisser. FDS Timing-enheter, designade och tillverkade i Schweiz, representerar branschens spets och erbjuder felfri prestanda under alla förhållanden.</p>
        <p className="mb-4">I ridsporttävlingar, som banhoppning och dressyr, måste tidtagningen inte bara vara exakt utan också sömlöst integrerad med resultatsystem. Equipe APP har blivit branschstandard, och vår utrustnings fulla kompatibilitet med detta system garanterar smidig tävlingshantering. Trådlösa fotoceller, stora och tydliga LED-poängtavlor samt pålitliga trådlösa sändare gör banbyggandet snabbt och resultatpresentationen publikvänlig. Eqilo Oy tillhandahåller allt som behövs, från små klubbtävlingar till stora internationella evenemang.</p>
        <p className="mb-4">Inom agility utgör hundarnas hastighet och banans komplexitet unika utmaningar för tidtagningsutrustningen. FDS Timings innovativa lösningar, som ultrasnabba och väderbeständiga fotoceller, garanterar att varje prestation mäts med millisekundprecision. Dessutom är vår utrustning byggd för att klara Finlands krävande väderförhållanden, från brännande solsken till kraftigt regn, vilket gör dem till ett idealiskt val för utomhustävlingar.</p>
        <p className="mb-4">På Eqilo Oy förstår vi att anskaffning av utrustning är en betydande investering för klubbar. Därför är vi inte bara en utrustningsleverantör, utan en partner. Vi erbjuder omfattande experttjänster för att hjälpa klubbar att välja den perfekta uppsättningen för deras behov och budget. Vårt långsiktiga mål är att sänka tröskeln för att införa professionell tidtagningsteknik i Finland. Modulariteten i FDS Timing-system gör det möjligt att utöka utrustningen i takt med att klubbens behov och resurser växer.</p>
        <p className="mb-4">Utöver inköp betonar Eqilo Oy vikten av utbildning och support. Även den bästa utrustningen är värdelös om användarna inte vet hur de ska utnyttja dess funktioner fullt ut. Vi erbjuder skräddarsydda utbildningssessioner som täcker både fysisk utrustningsuppsättning och programvaruanvändning, som Equipe APP. Våra experter är också tillgängliga under tävlingshelger för att hjälpa till med tekniska problem och säkerställa att evenemangen fortlöper smidigt.</p>
        <p className="mb-4">Schweizisk ingenjörskonst, synonymt med precision och kvalitet, är starkt närvarande i varje FDS Timing-produkt. Hållbarheten, den långa batteritiden och det intuitiva gränssnittet gör dem till pålitliga verktyg år efter år. Vi är stolta över att fungera som den officiella representanten för FDS Timing i Finland och ta dessa innovationer till lokala idrottare och arrangörer.</p>
        <p className="mb-4">Oavsett om du köper ett nytt tidtagningssystem, uppgraderar ett gammalt eller hyr utrustning för ett enskilt evenemang är Eqilo Oy redo att tjäna dig. Vi samlar ständigt in feedback från fältet och utvecklar våra tjänster för att bättre möta den finska idrottsgemenskapens behov. Utforska vårt utbud i vår onlinebutik eller kontakta våra experter för en personlig offert.</p>
        <p className="mb-4">När sporten blir alltmer digital växer förväntningarna på resultattjänster. Realtidsresultat online och på lokala displayer är inte längre en lyx, utan ett grundläggande krav. Lösningarna från Eqilo Oy möjliggör sömlös dataöverföring från banan till resultatsystemet och direkt till publiken. Detta förbättrar inte bara upplevelsen för tävlande och åskådare utan gör också arrangörernas arbete betydligt mer effektivt.</p>
        <p className="mb-4">Vi är också medvetna om vårt miljöansvar. FDS Timing-enheter är designade för lång livslängd, och deras modulära struktur gör det möjligt att reparera och uppdatera enskilda delar i stället för att byta ut hela systemet. Detta minskar elektroniskt avfall och erbjuder klubbar ett hållbart och kostnadseffektivt alternativ.</p>
        <p className="mb-4">Eqilo Oy:s historia började med en passion för sport och teknik. Vi vill vara med och utveckla den finska idrottskulturen genom att tillhandahålla verktyg som möjliggör rättvisare och mer professionella tävlingar. Ta steget mot bättre tidtagning och välj Eqilo Oy som din partner.</p>
      </div>
    );
  }

  return (
    <div className="prose prose-sm md:prose-base dark:prose-invert max-w-none mt-20 pt-10 border-t border-border/50 text-muted-foreground">
      <p className="mb-4">Professional-level timekeeping is the heartbeat of sports events. Eqilo Oy is dedicated to bringing world-class FDS Timing equipment to sports clubs and event organizers in Finland. We specialize particularly in timing solutions for equestrian sports and dog agility, where extreme precision and unwavering reliability are required. When milliseconds determine the winner, there is no room for compromise. Designed and manufactured in Switzerland, FDS Timing devices represent the pinnacle of the industry, offering flawless performance in all conditions.</p>
      <p className="mb-4">In equestrian competitions, such as show jumping and dressage, timekeeping must be not only accurate but also seamlessly integrated with results systems. The Equipe APP has become the industry standard, and our equipment's full compatibility with this system ensures smooth competition management. Wireless photocells, large and clear LED scoreboards, and reliable wireless transmitters make course building fast and result presentation audience-friendly. Eqilo Oy provides everything needed, from small club events to major international competitions.</p>
      <p className="mb-4">In agility, the speed of the dogs and the complexity of the course present unique challenges for timekeeping equipment. FDS Timing's innovative solutions, such as ultra-fast and weather-resistant photocells, guarantee that every performance is measured with millisecond precision. Furthermore, our equipment is built to withstand Finland's demanding weather conditions, from scorching sunshine to heavy rain, making them an ideal choice for outdoor competitions.</p>
      <p className="mb-4">At Eqilo Oy, we understand that acquiring equipment is a significant investment for clubs. That's why we are not just an equipment supplier, but a partner. We offer comprehensive expert services to help clubs choose the perfect setup for their needs and budget. Our long-term goal is to lower the barrier to adopting professional timekeeping technology in Finland. The modularity of FDS Timing systems allows the equipment to be expanded as the club's needs and resources grow.</p>
      <p className="mb-4">Beyond procurement, Eqilo Oy emphasizes the importance of training and support. Even the best equipment is useless if its users don't know how to fully utilize its features. We offer tailored training sessions covering both physical equipment setup and software usage, such as the Equipe APP. Our experts are also available during competition weekends to assist with any technical issues, ensuring events run smoothly.</p>
      <p className="mb-4">Swiss engineering, synonymous with precision and quality, is strongly evident in every FDS Timing product. The durability, long battery life, and intuitive interface make them reliable tools year after year. We are proud to serve as the official representative for FDS Timing in Finland, bringing these innovations to local athletes and organizers.</p>
      <p className="mb-4">Whether you are purchasing a new timekeeping system, upgrading an old one, or renting equipment for a single event, Eqilo Oy is ready to serve. We constantly gather feedback from the field and develop our services to better meet the needs of the Finnish sports community. Explore our selection in our online store or contact our experts for a personalized quote.</p>
      <p className="mb-4">As sports become increasingly digital, expectations for result services grow. Real-time results online and on local displays are no longer a luxury, but a fundamental requirement. The solutions provided by Eqilo Oy enable seamless data transfer from the course to the results system and straight to the audience. This not only enhances the experience for competitors and spectators but also makes the organizers' work significantly more efficient.</p>
      <p className="mb-4">We are also mindful of our environmental responsibility. FDS Timing devices are designed for longevity, and their modular structure allows for individual parts to be repaired and updated instead of replacing the entire system. This reduces electronic waste and offers clubs a sustainable and cost-effective alternative.</p>
      <p className="mb-4">Eqilo Oy's story began with a passion for sports and technology. We want to be part of developing Finnish sports culture by providing tools that enable fairer and more professional competitions. Take the step towards better timekeeping and choose Eqilo Oy as your partner.</p>
    </div>
  );
}
