
"use client";
import { useLanguage } from "@/components/language-provider";

export function SEOContent() {
  const { lang } = useLanguage();
  
  if (lang === "FI") {
    return (
      <div className="prose prose-sm md:prose-base dark:prose-invert max-w-none mt-20 pt-10 border-t border-border/50 text-muted-foreground">
        <p className="mb-4">Ammattilaistason ajanottolaitteiden hankinta on kriittinen päätös urheiluseuroille ja tapahtumajärjestäjille. Eqilo Oy:n verkkokauppa tarjoaa kattavan valikoiman FDS Timing -tuotteita, jotka on suunniteltu vastaamaan nykyaikaisen urheilun kovimpiin vaatimuksiin. Valikoimastamme löydät kaiken tarvittavan täydellisen ajanottojärjestelmän rakentamiseen: langattomat valokennot, tarkat ajanottokellot, selkeät näyttötaulut sekä kaikki vaadittavat kaapelit ja oheislaitteet. Jokainen tuote edustaa sveitsiläistä laatua ja innovaatiota, taaten luotettavuuden kaikissa olosuhteissa.</p>
        <p className="mb-4">Oikean laitteiston valinta riippuu monesta tekijästä, kuten lajista, tapahtuman koosta ja budjetista. Esimerkiksi ratsastuksessa ja agilityssä laitteiden on oltava nopeasti siirrettävissä ja asennettavissa, mikä tekee FDS Timingin langattomista ratkaisuista erinomaisen valinnan. Valokennot reagoivat millisekuntien tarkkuudella, ja TBOX-radiomodeemit siirtävät tiedon luotettavasti ajanottokellolle pitkienkin välimatkojen päästä. Me Eqilossa autamme mielellämme rakentamaan juuri teidän tarpeitanne vastaavan paketin.</p>
        <p className="mb-4">Näyttötaulut ovat olennainen osa yleisökokemusta. Valikoimamme LED-näytöt ovat kirkkaita ja helposti luettavissa jopa suorassa auringonpaisteessa. Ne voidaan integroida saumattomasti Equipe APP -ohjelmistoon, jolloin tulokset ja ajat päivittyvät taululle reaaliajassa. Tämä ei ainoastaan paranna katsojien viihtyvyyttä, vaan myös vähentää kuuluttajan työtaakkaa ja minimoi inhimillisten virheiden mahdollisuuden.</p>
        <p className="mb-4">Ajanottojärjestelmän sydän on itse ajanottokello, joka prosessoi valokennoilta saapuvan tiedon. FDS Timingin kellot ovat äärimmäisen tarkkoja ja helppokäyttöisiä. Ne tukevat useita eri lajiprofiileja ja mahdollistavat monimutkaistenkin kilpailusääntöjen ohjelmoinnin laitteeseen. Pitkä akkukesto ja kestävä rakenne takaavat, että kello toimii moitteettomasti pitkienkin kilpailupäivien ajan.</p>
        <p className="mb-4">Kaikki elektroniset laitteet vaativat säännöllistä huoltoa ja oikeanlaista säilytystä toimiakseen luotettavasti. Tarjoamme valikoiman laadukkaita suojalaukkuja ja tarvikkeita laitteiden turvalliseen kuljetukseen. Lisäksi Eqilo Oy tarjoaa ammattitaitoista huoltopalvelua ja varaosia kaikkiin myymiimme FDS Timing -tuotteisiin. Tämä pidentää laitteiston käyttöikää ja maksimoi investointinne arvon.</p>
        <p className="mb-4">Ymmärrämme, että seurojen budjetit voivat olla tiukkoja. Siksi tarjoamme joustavia ratkaisuja laitteiden hankintaan. Modulaarisen järjestelmän ansiosta voitte aloittaa peruskokoonpanolla ja laajentaa sitä myöhemmin tarpeiden kasvaessa. Esimerkiksi yksinkertainen langallinen järjestelmä voidaan myöhemmin päivittää langattomaksi lisäämällä siihen radiomodeemit. Kysy asiantuntijoiltamme neuvoa parhaan ratkaisun löytämiseksi.</p>
        <p className="mb-4">Digitaalinen tulospalvelu on nykypäivää, ja laitteidemme yhteensopivuus alan johtavien ohjelmistojen kanssa on yksi suurimmista valteistamme. Equipe APP on suosittu valinta monissa lajeissa, ja FDS Timing -laitteet on suunniteltu toimimaan saumattomasti sen kanssa. Tarjoamme myös tukea ja koulutusta ohjelmistojen käyttöön, jotta saatte laitteistostanne kaiken irti.</p>
        <p className="mb-4">Kutsumme kaikki suomalaiset urheiluseurat tutustumaan valikoimaamme ja päivittämään ajanottoratkaisunsa tälle vuosituhannelle. Ammattimainen laitteisto ei ainoastaan tee kilpailuista reilumpia ja tarkempia, vaan se myös viestii tapahtuman korkeasta laadusta kilpailijoille ja yleisölle. Eqilo Oy on ylpeä voidessaan tukea suomalaista urheilua tarjoamalla maailman parasta ajanottoteknologiaa.</p>
        <p className="mb-4">Asiakastyytyväisyys on meille ykkösprioriteetti. Siksi tarjoamme nopean toimituksen Suomeen ja asiantuntevaa tukea suomeksi, englanniksi ja ruotsiksi. Tavoitteenamme on olla enemmän kuin vain verkkokauppa – haluamme olla luotettava kumppani, johon voitte luottaa kaikissa ajanottoon liittyvissä asioissa.</p>
        <p className="mb-4">Selaa kategorioitamme, vertaile tuotteita ja löydä täydellinen ratkaisu seurallenne. Jos et löydä etsimääsi tai tarvitset apua valinnassa, älä epäröi ottaa yhteyttä asiakaspalveluumme. Eqilo Oy – tarkkaa aikaa, parempia tapahtumia.</p>
      </div>
    );
  }
  
  if (lang === "SE") {
    return (
      <div className="prose prose-sm md:prose-base dark:prose-invert max-w-none mt-20 pt-10 border-t border-border/50 text-muted-foreground">
        <p className="mb-4">Att förvärva tidtagningsutrustning på professionell nivå är ett avgörande beslut för idrottsklubbar och evenemangsorganisatörer. Eqilo Oys onlinebutik erbjuder ett omfattande urval av FDS Timing-produkter designade för att möta moderna sporters tuffaste krav. I vårt sortiment hittar du allt som behövs för att bygga ett komplett tidtagningssystem: trådlösa fotoceller, exakta kronometrar, tydliga displaytavlor samt alla nödvändiga kablar och kringutrustning. Varje produkt representerar schweizisk kvalitet och innovation, vilket säkerställer tillförlitlighet under alla förhållanden.</p>
        <p className="mb-4">Att välja rätt utrustning beror på många faktorer, såsom sport, evenemangsstorlek och budget. Inom ridsport och agility måste utrustningen till exempel vara snabb att flytta och installera, vilket gör FDS Timings trådlösa lösningar till ett utmärkt val. Fotocellerna reagerar med millisekundsprecision, och TBOX-radiomodemen överför data pålitligt till kronometern även över långa avstånd. På Eqilo hjälper vi dig gärna att bygga ett paket som uppfyller exakt dina behov.</p>
        <p className="mb-4">Displaytavlor är en viktig del av publikupplevelsen. Vårt urval av LED-displayer är ljusstarkt och lättläst även i direkt solljus. De kan sömlöst integreras med Equipe APP-programvaran, vilket gör att resultat och tider uppdateras på tavlan i realtid. Detta förbättrar inte bara åskådarnas njutning utan minskar också speakerns arbetsbelastning och minimerar risken för mänskliga fel.</p>
        <p className="mb-4">Hjärtat i tidtagningssystemet är själva kronometern, som bearbetar inkommande data från fotocellerna. FDS Timings kronometrar är extremt exakta och användarvänliga. De stöder flera sportprofiler och tillåter programmering av komplexa tävlingsregler direkt i enheten. Lång batteritid och hållbar konstruktion säkerställer att klockan fungerar felfritt under långa tävlingsdagar.</p>
        <p className="mb-4">Alla elektroniska enheter kräver regelbundet underhåll och korrekt förvaring för att fungera pålitligt. Vi erbjuder ett urval av högkvalitativa skyddsväskor och tillbehör för säker transport av din utrustning. Dessutom erbjuder Eqilo Oy professionella underhållstjänster och reservdelar för alla FDS Timing-produkter vi säljer. Detta förlänger utrustningens livslängd och maximerar värdet på din investering.</p>
        <p className="mb-4">Vi förstår att klubbbudgetar kan vara strama. Därför erbjuder vi flexibla lösningar för anskaffning av utrustning. Tack vare det modulära systemet kan du börja med en grundläggande uppsättning och bygga ut den senare när dina behov växer. Ett enkelt trådbundet system kan till exempel senare uppgraderas till trådlöst genom att lägga till radiomodem. Fråga våra experter om råd för att hitta den bästa lösningen.</p>
        <p className="mb-4">Digitala resultattjänster är normen idag, och vår utrustnings kompatibilitet med branschledande programvara är en av våra största fördelar. Equipe APP är ett populärt val inom många sporter, och FDS Timing-enheter är designade för att fungera sömlöst med den. Vi erbjuder även support och utbildning i hur man använder programvaran för att säkerställa att du får ut det mesta av din utrustning.</p>
        <p className="mb-4">Vi inbjuder alla finska idrottsklubbar att utforska vårt urval och uppdatera sina tidtagningslösningar till den moderna eran. Professionell utrustning gör inte bara tävlingar rättvisare och mer exakta utan signalerar också evenemangets höga kvalitet till tävlande och publik. Eqilo Oy är stolta över att stödja finsk idrott genom att erbjuda den bästa tidtagningstekniken i världen.</p>
        <p className="mb-4">Kundnöjdhet är vår högsta prioritet. Därför erbjuder vi snabb leverans inom Finland och expertsupport på finska, engelska och svenska. Vårt mål är att vara mer än bara en onlinebutik – vi vill vara en pålitlig partner du kan lita på i alla tidtagningsärenden.</p>
        <p className="mb-4">Bläddra bland våra kategorier, jämför produkter och hitta den perfekta lösningen för din klubb. Om du inte hittar det du letar efter eller behöver hjälp med att välja, tveka inte att kontakta vår kundtjänst. Eqilo Oy – exakt tid, bättre evenemang.</p>
      </div>
    );
  }

  return (
    <div className="prose prose-sm md:prose-base dark:prose-invert max-w-none mt-20 pt-10 border-t border-border/50 text-muted-foreground">
      <p className="mb-4">Acquiring professional-level timekeeping equipment is a critical decision for sports clubs and event organizers. Eqilo Oy's online store offers a comprehensive selection of FDS Timing products designed to meet the toughest demands of modern sports. In our range, you will find everything needed to build a complete timekeeping system: wireless photocells, precise chronometers, clear display boards, and all required cables and peripherals. Every product represents Swiss quality and innovation, ensuring reliability in all conditions.</p>
      <p className="mb-4">Choosing the right equipment depends on many factors, such as the sport, event size, and budget. In equestrian and agility, for example, equipment must be quick to move and install, making FDS Timing's wireless solutions an excellent choice. The photocells react with millisecond precision, and the TBOX radio modems transfer data reliably to the chronometer even over long distances. At Eqilo, we are happy to help build a package that meets your exact needs.</p>
      <p className="mb-4">Display boards are an essential part of the audience experience. Our selection of LED displays is bright and easily readable even in direct sunlight. They can be seamlessly integrated with the Equipe APP software, allowing results and times to update on the board in real time. This not only improves spectator enjoyment but also reduces the announcer's workload and minimizes the possibility of human error.</p>
      <p className="mb-4">The heart of the timekeeping system is the chronometer itself, which processes the incoming data from the photocells. FDS Timing's chronometers are extremely accurate and user-friendly. They support multiple sport profiles and allow the programming of complex competition rules directly into the device. Long battery life and durable construction ensure the clock works flawlessly throughout long competition days.</p>
      <p className="mb-4">All electronic devices require regular maintenance and proper storage to function reliably. We offer a selection of high-quality protective cases and accessories for the safe transport of your equipment. In addition, Eqilo Oy provides professional maintenance services and spare parts for all FDS Timing products we sell. This extends the lifespan of the equipment and maximizes the value of your investment.</p>
      <p className="mb-4">We understand that club budgets can be tight. That's why we offer flexible solutions for acquiring equipment. Thanks to the modular system, you can start with a basic setup and expand it later as your needs grow. For example, a simple wired system can later be upgraded to wireless by adding radio modems. Ask our experts for advice on finding the best solution.</p>
      <p className="mb-4">Digital results services are the norm today, and the compatibility of our equipment with industry-leading software is one of our biggest advantages. The Equipe APP is a popular choice in many sports, and FDS Timing devices are designed to work seamlessly with it. We also provide support and training on using the software to ensure you get the most out of your equipment.</p>
      <p className="mb-4">We invite all Finnish sports clubs to explore our selection and update their timekeeping solutions to the modern era. Professional equipment not only makes competitions fairer and more accurate but also signals the high quality of the event to competitors and the audience. Eqilo Oy is proud to support Finnish sports by offering the best timekeeping technology in the world.</p>
      <p className="mb-4">Customer satisfaction is our top priority. That's why we offer fast delivery within Finland and expert support in Finnish, English, and Swedish. Our goal is to be more than just an online store – we want to be a reliable partner you can trust in all timekeeping matters.</p>
      <p className="mb-4">Browse our categories, compare products, and find the perfect solution for your club. If you don't find what you're looking for or need help choosing, don't hesitate to contact our customer service. Eqilo Oy – precise time, better events.</p>
    </div>
  );
}
