"use client";

import React, { createContext, useContext, useState, useEffect } from "react";

type Language = "FI" | "EN" | "SE";

interface TranslationDictionary {
  [key: string]: string;
}

const dictionaries: Record<Language, TranslationDictionary> = {
  FI: {
    "nav.products": "Tuotteet",
    "nav.services": "Palvelut",
    "nav.consulting": "Eqilo Konsultointi",
    "nav.training": "Koulutus & Tulospalvelu",
    "nav.equipe": "Equipe Ohjelmisto",
    "nav.cart": "Ostoskori",
    "nav.admin": "Hallintapaneeli",
    "nav.login": "Kirjaudu Sisään",
    "nav.logout": "Kirjaudu Ulos",
    "nav.my_orders": "Omat Tilaukset",
    "nav.profile": "Profiili",
    "nav.terms": "Käyttöehdot",
    "nav.privacy": "Tietosuojaseloste",
    "nav.cookie": "Evästekäytäntö",
    "nav.sports": "Urheilulajit",
    "nav.contact_us": "Ota Yhteyttä",
    "nav.consulting_desc": "Yli 20 vuoden kokemus kilpailu- ja ajanottojärjestelmistä.",
    "nav.training_desc": "Kenttätoiminta ja henkilökunnan koulutus.",
    "nav.equipe_desc": "Hevosurheilun kilpailunhallinnan standardi.",
    "nav.search_sr": "Etsi tuotteita",
    "nav.language": "Kieli",
    "home.hero.title": "Modernit ajanottoratkaisut ammattilaisille",
    "home.hero.subtitle": "Eqilo.fi tuo sveitsiläisen FDS Timing -teknologian suomalaisiin agility- ja ratsastusseuroihin. Langaton, säänkestävä ja saumattomasti integroituva.",
    "home.hero.shop": "Osta Laitteita",
    "home.hero.services": "Palvelumme",
    "home.partners.title": "Yhteistyössä",
    "home.advantages.title": "FDS Timingin edut",
    "home.advantages.subtitle": "Miksi seurat ympäri Suomea valitsevat nykyaikaiset FDS Timing -laitteet.",
    "home.advantage.wireless.title": "100% Langaton",
    "home.advantage.wireless.desc": "Helppo käyttää ja nopea asentaa. Ei häiritseviä kaapeleita kentällä.",
    "home.advantage.battery.title": "Sisäänrakennettu akku",
    "home.advantage.battery.desc": "Moderni ja kompakti teknologia. Ei kömpelöitä ulkoisia akkuja.",
    "home.advantage.software.title": "Ohjelmistoyhteensopiva",
    "home.advantage.software.desc": "Suora integraatio suosittuihin tulospalveluihin, kuten Equipeen.",
    "home.advantage.weather.title": "Säänkestävä",
    "home.advantage.weather.desc": "Vankka rakenne takaa luotettavan toiminnan vaativissa olosuhteissa.",
    "home.advantage.cost.title": "Kustannustehokas",
    "home.advantage.cost.desc": "Kohtuullinen hinta verrattuna vanhoihin, raskaisiin perinteisiin järjestelmiin.",
    "home.advantage.more.title": "Lue lisää",
    "home.advantage.more.desc": "Sopii kaikille tasoille seurakilpailuista kansainvälisiin arvokisoihin.",
    "home.advantage.more.button": "Selaa tuotteita",
    "home.services.title": "20 vuoden asiantuntemus",
    "home.services.desc": "Laitteiden myynnin lisäksi tarjoamme kilpailukonsultointia, teknistä tukea, huoltoa ja dedikoitua koulutusta ajanottojärjestelmiin.",
    "home.services.button": "Tutustu palveluihimme",
    "home.services.expert_cta": "Tarvitsetko asiantuntijaa tapahtumaasi?",
    "home.services.expert_desc": "Johannes Hyrsky ja Eqilon tiimi ovat valmiina auttamaan.",
    "home.quote.text": "\"Tavoitteemme on parantaa nykyaikaisten ajanottoratkaisujen saatavuutta Suomessa ja madaltaa seurojen kynnystä ammattiteknologian käyttöön.\"",
    "home.quote.author": "Johannes Hyrsky",
    "home.quote.role": "Kauppias & Asiantuntija",
    "shop.all_equipment": "Kaikki Laitteet",
    "shop.categories": "Kategoriat",
    "shop.view_details": "Katso Tiedot",
    "shop.items_found": "tuotetta löytyi",
    "shop.in_stock": "Varastossa",
    "shop.add": "Lisää",
    "shop.price": "Hinta",
    "shop.description": "Ammattimaiset ajanottoratkaisut seuroille.",
    "shop.loading": "Ladataan ammattilaitteita...",
    "product.sku": "Tuotekoodi",
    "product.incl_vat": "sis. alv",
    "product.standard_shipping": "Vakiotoimitus: 1-2 viikkoa",
    "product.shipping_details": "Tuotteet toimitetaan suoraan Suomeen. Ilmainen toimitus yli 200 € tilauksiin.",
    "product.add_to_cart": "Lisää ostoskoriin",
    "product.description": "Kuvaus",
    "product.specs": "Tekniset tiedot",
    "product.weight": "Paino",
    "product.category": "Kategoria",
    "product.box_contents": "Pakkauksen sisältö",
    "product.downloads": "Lataukset",
    "product.guarantee": "Laatutakuu",
    "product.loading": "Ladataan tuotetietoja...",
    "product.image_pending": "Tuotekuva tulossa",
    "product.customize_kit": "Räätälöi pakettisi",
    "product.quantity": "Määrä",
    "product.guarantee_desc": "Kaikilla FDS Timing -laitteilla on sveitsiläinen laatutakuu ja Eqilon yli 20 vuoden paikallinen asiantuntijatuki.",
    "category.after-sales": "Huoltopalvelut",
    "category.peripheral": "Oheislaitteet",
    "category.display": "Näytöt",
    "category.cables": "Kaapelit",
    "category.accessories": "Tarvikkeet",
    "category.ios-app": "iOS-sovellus",
    "category.kit": "Tuotepaketit",
    "category.timer": "Ajanottolaitteet",
    "category.loading": "Ladataan...",
    "category.empty": "Tästä kategoriasta ei löytynyt tuotteita.",
    "category.description_prefix": "Ammattimaiset FDS Timing -ratkaisut kategoriaan",
    "cart.title": "Ostoskori",
    "cart.empty": "Ostoskorisi on tyhjä",
    "cart.empty_sub": "Et ole vielä lisännyt FDS Timing -laitteita ostoskoriisi.",
    "cart.browse": "Selaa tuotteita",
    "cart.summary": "Tilausyhteenveto",
    "cart.subtotal": "Välisumma",
    "cart.shipping": "Toimitus (Suomi)",
    "cart.total": "Yhteensä",
    "cart.checkout": "Siirry kassalle",
    "cart.request_quote": "Lataa virallinen tarjous (PDF)",
    "cart.remove": "Poista",
    "cart.updating": "Päivitetään ostoskoria...",
    "cart.clear_all": "Tyhjennä",
    "cart.items_in_cart": "tuotetta ostoskorissa",
    "cart.unit": "kpl",
    "cart.free": "Ilmainen",
    "cart.or": "TAI",
    "checkout.title": "Kassa",
    "checkout.billing": "Laskutustiedot",
    "checkout.place_order": "Maksa tilaus",
    "checkout.loading": "Valmistellaan kassaa...",
    "checkout.b2b_note": "Vaaditaan B2B-laskutusta ja ALV-käsittelyä varten",
    "checkout.stripe_note": "Maksut käsitellään turvallisesti Stripen kautta. Tietosi on salattu eikä niitä tallenneta palvelimillemme.",
    "checkout.terms_agree": "Hyväksyn kaupan käyttöehdot",
    "checkout.optional": "Valinnainen",
    "checkout.success_title": "Tilaus vahvistettu!",
    "checkout.success_desc": "Kiitos ostoksestasi. Tilauksesi on nyt käsittelyssä.",
    "checkout.order_ref": "Tilausviite",
    "checkout.status": "Tila",
    "checkout.total_paid": "Yhteensä maksettu",
    "checkout.email_sent": "Vahvistussähköposti on lähetetty osoitteeseen",
    "checkout.shipping_note": "FDS Timing -laitteiden vakiotoimitusaika on 1-2 viikkoa.",
    "checkout.continue_shopping": "Jatka ostoksia",
    "checkout.explore_services": "Tutustu palveluihimme",
    "checkout.login_required": "Kirjaudu sisään jatkaaksesi kassalle.",
    "auth.email": "Sähköposti",
    "auth.phone": "Puhelinnumero",
    "auth.password": "Salasana",
    "auth.login": "Kirjaudu",
    "auth.register": "Rekisteröidy",
    "auth.verify": "Vahvista koodi",
    "auth.send_code": "Lähetä koodi",
    "auth.or": "TAI",
    "auth.login_title": "Tervetuloa takaisin",
    "auth.register_title": "Luo tili",
    "auth.need_account": "Tarvitsetko tilin? Rekisteröidy",
    "auth.already_have_account": "Onko sinulla jo tili? Kirjaudu",
    "auth.sms_code": "Tekstiviestikoodi",
    "auth.login_desc": "Kirjaudu sisään hallinnoidaksesi tilauksiasi ja tallennettuja ostoskoreja.",
    "auth.register_desc": "Liity Eqilo.fi-palveluun hallinnoidaksesi ammattilaitteitasi.",
    "auth.phone_note": "Sisällytä maakoodi (esim. +358).",
    "auth.otp_label": "Vahvistuskoodi",
    "auth.back": "Takaisin",
    "orders.loading": "Ladataan tilauksiasi...",
    "orders.description": "Seuraa FDS Timing -laitteidesi toimituksia.",
    "orders.empty": "Tilauksia ei löytynyt",
    "orders.empty_sub": "Et ole vielä tehnyt tilauksia.",
    "orders.id": "Tilausnumero",
    "orders.date": "Päivämäärä",
    "orders.items": "Tilauksen sisältö",
    "orders.delivery_details": "Toimitustiedot",
    "orders.tracking": "Lähetyksen seuranta",
    "orders.product_id": "Tuotenumero",
    "orders.tax_breakdown": "Veron erittely",
    "orders.track_button": "Seuraa",
    "orders.paid": "Maksettu",
    "orders.processing": "Käsitellään",
    "orders.shipped": "Lähetetty",
    "orders.delivered": "Toimitettu",
    "quote.title": "Pyydä virallinen tarjous",
    "quote.desc": "Syötä organisaatiosi tiedot. Luomme virallisen PDF-tarjouksen hallituksen hyväksyntää varten ja lähetämme kopion sähköpostiisi.",
    "quote.org_name": "Seura / Organisaatio",
    "quote.contact_person": "Yhteyshenkilö",
    "quote.reference": "Viite",
    "quote.generating": "Luodaan...",
    "quote.download_button": "Lataa ja lähetä tarjous",
    "services.title": "Asiantuntemus & Palvelut",
    "services.subtitle": "Ammattimaiset ajanottoratkaisut ja asiantuntijapalvelut.",
    "services.equipe_cta": "Tutustu Equipe-asetuksiin",
    "services.training_cta": "Tutustu koulutuspalveluun",
    "services.equipe_desc_short": "Equestrian kilpailujen hallinnan asiantuntijat.",
    "services.training_desc_short": "Kattava kenttätoiminta, koulutus ja konsultointi.",
    "services.equipe_full": "Hevosurheilutapahtumien asiantuntijoina tarjoamme täydellisen integraation, asennuksen ja tuen Equipe-ohjelmistoekosysteemille. Yhdistämme FDS Timing -laitteistosi suoraan digitaaliseen tulostauluun.",
    "services.training_full": "Tarjoamme syvällistä ja käytännönläheistä tukea tapahtumillesi. Olipa kyseessä paikallinen seuran kilpailu tai massiivinen kansainvälinen turnaus, kenttäkoulutuksemme varmistaa, että henkilökuntasi on itsevarma ja tulokset virheettömiä.",
    "services.feature.on_site": "Henkilökunnan koulutus paikan päällä",
    "services.feature.setup": "Laitteiston asennus ja purku",
    "services.feature.live": "Live-tulospalvelun hallinta",
    "services.feature.bridge": "Ohjelmisto-laitteisto -silta",
    "services.feature.auto": "Automatisoidut ajanottosyötteet",
    "services.feature.config": "Mukautetut kilpailuasetukset",
    "equipe.title": "Equipe Ohjelmisto & Integraatio",
    "equipe.subtitle": "Hevosurheilun Standardi",
    "equipe.desc": "Olemme hevosurheilun kilpailunhallinnan asiantuntijoita. Eqilo tarjoaa täyden tuen maailman johtavalle kilpailunhallintajärjestelmälle.",
    "equipe.visit": "Vieraile Equipe.comissa",
    "equipe.live": "Livetulokset & Lähtölistat",
    "equipe.live_desc": "Täydellinen reaaliaikainen näkyvyys yleisölle.",
    "equipe.feature1.title": "Laitteistointegraatio",
    "equipe.feature1.desc": "Yhdistämme FDS Timing -laitteesi suoraan Equipeen automaattisia aikapäivityksiä varten.",
    "equipe.feature2.title": "Verkkopalvelut",
    "equipe.feature2.desc": "Lähtölistojen, tulosten ja live-lähetysten hallinta pilvipalveluna.",
    "equipe.feature3.title": "Räätälöinti",
    "equipe.feature3.desc": "Kilpailujen sääntöjen ja asetusten konfigurointi suomalaisiin tarpeisiin.",
    "equipe.cta_title": "Valmiina modernisoimaan kilpailusi?",
    "equipe.cta_desc": "Olemme auttaneet kymmeniä seuroja ottamaan digitaalisen harppauksen. Ota yhteyttä ja suunnitellaan teille sopiva kokonaisuus.",
    "equipe.browse": "Tutustu laitteistoon",
    "search.placeholder": "Etsi tuotteita nimellä tai koodilla...",
    "search.no_results": "Tuotteita ei löytynyt.",
    "search.results": "Hakutulokset",
    "search.suggested": "Suositellut tuotteet",
    "footer.company": "Yritys",
    "footer.store": "Kauppa",
    "footer.partners": "Kumppanit",
    "footer.terms": "Käyttöehdot",
    "footer.business_id": "Y-Tunnus",
    "footer.rights": "Kaikki oikeudet pidätetään.",
    "footer.company_desc": "Modernit ajanottolaitteet sveitsiläiseltä FDS Timingilta. Eqilo tarjoaa yli 20 vuoden asiantuntemusta suomalaisille agility- ja ratsastusseuroille.",
    "cookie.title": "Yksityisyytesi on meille tärkeää",
    "cookie.desc": "Käytämme evästeitä parantaaksemme sivuston käyttökokemusta, tarjotaksemme kohdennettua sisältöä ja analysoidaksemme liikennettä.",
    "cookie.accept": "Hyväksy kaikki",
    "cookie.decline": "Vain välttämättömät",
    "whatsapp.chat": "Keskustele WhatsAppissa",
    "whatsapp.online": "Paikalla",
    "whatsapp.welcome": "Moi! Miten voin auttaa sinua tänään ajanottolaitteisiin liittyen?",
    "whatsapp.scan_title": "Skannaa ja keskustele",
    "whatsapp.scan_desc": "Avaa WhatsApp skannaamalla koodi puhelimellasi.",
    "whatsapp.web_link": "Tai klikkaa tästä WhatsApp Webiin",
    "whatsapp.ask_johannes": "Kysy Johannekselta",
  },
  EN: {
    "nav.products": "Products",
    "nav.services": "Services",
    "nav.consulting": "Eqilo Consulting",
    "nav.training": "Training & Results",
    "nav.equipe": "Equipe Software",
    "nav.cart": "Cart",
    "nav.admin": "Admin Portal",
    "nav.login": "Sign In",
    "nav.logout": "Sign Out",
    "nav.my_orders": "My Orders",
    "nav.profile": "Profile",
    "nav.terms": "Terms & Conditions",
    "nav.privacy": "Privacy Policy",
    "nav.cookie": "Cookie Policy",
    "nav.contact_us": "Contact Us",
    "nav.consulting_desc": "20+ years of expertise in competition and timekeeping systems.",
    "nav.training_desc": "On-site operations and staff training.",
    "nav.equipe_desc": "The standard for equestrian show management.",
    "nav.search_sr": "Search products",
    "nav.language": "Language",
    "home.hero.title": "Modern Timekeeping Solutions for Professionals",
    "home.hero.subtitle": "Eqilo.fi brings Swiss-engineered FDS Timing technology to Finnish agility and equestrian clubs. Wireless, weatherproof, and seamlessly integrated.",
    "home.hero.shop": "Shop Equipment",
    "home.hero.services": "Our Services",
    "home.partners.title": "Trusted By & Official Partner Of",
    "home.advantages.title": "The FDS Timing Advantage",
    "home.advantages.subtitle": "Why clubs across Finland are upgrading to modern FDS Timing equipment.",
    "home.advantage.wireless.title": "100% Wireless",
    "home.advantage.wireless.desc": "Easy to use and quick to deploy. No external cables required on the field.",
    "home.advantage.battery.title": "Built-in Battery",
    "home.advantage.battery.desc": "Modern and compact technology. No clunky external battery packs to manage.",
    "home.advantage.software.title": "Software Compatible",
    "home.advantage.software.desc": "Direct integration with popular results services like Equipe and SmarterAgility.",
    "home.advantage.weather.title": "Weatherproof",
    "home.advantage.weather.desc": "Robust construction ensuring reliable performance in demanding environments.",
    "home.advantage.cost.title": "Cost-Effective",
    "home.advantage.cost.desc": "Reasonable cost compared to legacy, heavy traditional systems.",
    "home.advantage.more.title": "Explore More",
    "home.advantage.more.desc": "Suitable for all event levels from club competitions to international events.",
    "home.advantage.more.button": "Browse Catalog",
    "home.services.title": "20 Years of Expertise",
    "home.services.desc": "Beyond equipment sales, we provide competition consultation, technical support, equipment service, and dedicated training for timekeeping and results systems.",
    "home.services.button": "Discover Our Services",
    "home.services.expert_cta": "Need an expert for your event?",
    "home.services.expert_desc": "Johannes Hyrsky and the Eqilo team are ready to help.",
    "home.quote.text": "\"Our goal is to significantly improve accessibility to modern timekeeping solutions in Finland, lowering the barrier for clubs to adopt professional-level technology.\"",
    "home.quote.author": "Johannes Hyrsky",
    "home.quote.role": "Store Owner & Expert",
    "shop.all_equipment": "All Equipment",
    "shop.categories": "Categories",
    "shop.view_details": "View Details",
    "shop.items_found": "items found",
    "shop.in_stock": "In Stock",
    "shop.add": "Add",
    "shop.price": "Price",
    "shop.description": "Professional timekeeping solutions for clubs.",
    "shop.loading": "Loading professional equipment...",
    "product.sku": "SKU",
    "product.incl_vat": "incl. VAT",
    "product.vat_amount": "VAT amount",
    "product.net_price": "Net (0% VAT)",
    "product.standard_shipping": "Standard Shipping: 1-2 Weeks",
    "product.shipping_details": "Products are shipped directly to Finland. Free shipping on orders over 200 €.",
    "product.add_to_cart": "Add to Cart",
    "product.description": "Description",
    "product.specs": "Specifications",
    "product.weight": "Weight",
    "product.category": "Category",
    "product.box_contents": "Box Contents",
    "product.downloads": "Downloads & Manuals",
    "product.videos": "Tutorial Videos",
    "product.guarantee": "Quality Guarantee",
    "product.loading": "Loading equipment details...",
    "product.image_pending": "Product Image Pending",
    "product.customize_kit": "Customize Your Kit",
    "product.quantity": "Quantity",
    "product.related": "Frequently Bought Together",
    "product.guarantee_desc": "All FDS Timing devices are backed by Swiss-engineered reliability and supported locally by Eqilo's 20 years of expertise.",
    "category.after-sales": "After-Sales",
    "category.peripheral": "Peripherals",
    "category.display": "Displays",
    "category.cables": "Cables",
    "category.accessories": "Accessories",
    "category.ios-app": "iOS App",
    "category.kit": "Kits",
    "category.timer": "Timers",
    "category.loading": "Loading...",
    "category.empty": "No products found in this category.",
    "category.description_prefix": "Professional FDS Timing solutions for",
    "cart.title": "Shopping Cart",
    "cart.empty": "Your cart is empty",
    "cart.empty_sub": "Looks like you haven't added any FDS Timing equipment to your cart yet.",
    "cart.browse": "Browse Products",
    "cart.summary": "Order Summary",
    "cart.subtotal": "Subtotal",
    "cart.shipping": "Shipping (Finland)",
    "cart.total": "Total",
    "cart.checkout": "Proceed to Checkout",
    "cart.request_quote": "Request Official Quote (PDF)",
    "cart.remove": "Remove",
    "cart.updating": "Updating your cart...",
    "cart.clear_all": "Clear All",
    "cart.items_in_cart": "items in cart",
    "cart.unit": "each",
    "cart.free": "Free",
    "cart.or": "OR",
    "checkout.title": "Checkout",
    "checkout.billing": "Billing Details",
    "checkout.place_order": "Place Order",
    "checkout.loading": "Preparing checkout...",
    "checkout.b2b_note": "Required for B2B Invoice & VAT handling",
    "checkout.stripe_note": "Payments are securely processed by Stripe. Your data is encrypted and never stored on our servers.",
    "checkout.terms_agree": "I accept the store terms & conditions",
    "checkout.optional": "Optional",
    "checkout.success_title": "Order Confirmed!",
    "checkout.success_desc": "Thank you for your purchase. Your order is now being processed.",
    "checkout.order_ref": "Order Reference",
    "checkout.status": "Status",
    "checkout.total_paid": "Total Paid",
    "checkout.email_sent": "A confirmation email has been sent to",
    "checkout.shipping_note": "Standard delivery for FDS Timing equipment is 1-2 weeks.",
    "checkout.continue_shopping": "Continue Shopping",
    "checkout.explore_services": "Explore Our Services",
    "checkout.login_required": "Please sign in to continue to checkout.",
    "auth.email": "Email",
    "auth.phone": "Phone Number",
    "auth.password": "Password",
    "auth.login": "Log in",
    "auth.register": "Register",
    "auth.verify": "Verify Code",
    "auth.send_code": "Send Code",
    "auth.or": "OR",
    "auth.login_title": "Welcome Back",
    "auth.register_title": "Create Account",
    "auth.need_account": "Need an account? Register",
    "auth.already_have_account": "Already have an account? Log in",
    "auth.sms_code": "SMS Code",
    "auth.login_desc": "Sign in to access your orders and saved carts.",
    "auth.register_desc": "Join Eqilo.fi to manage your professional equipment.",
    "auth.phone_note": "Include country code (e.g., +358).",
    "auth.otp_label": "Verification Code",
    "auth.back": "Back",
    "orders.loading": "Loading your orders...",
    "orders.description": "Track your FDS Timing equipment deliveries.",
    "orders.empty": "No orders found",
    "orders.empty_sub": "You haven't placed any orders yet.",
    "orders.id": "Order ID",
    "orders.date": "Date",
    "orders.items": "Order Items",
    "orders.delivery_details": "Delivery Details",
    "orders.tracking": "Tracking Information",
    "orders.product_id": "Product ID",
    "orders.tax_breakdown": "Tax Breakdown",
    "orders.track_button": "Track",
    "orders.paid": "Paid",
    "orders.processing": "Processing",
    "orders.shipped": "Shipped",
    "orders.delivered": "Delivered",
    "quote.title": "Request Official Quote",
    "quote.desc": "Enter your organization details. We'll generate a formal PDF for your board approval and email a copy to you.",
    "quote.org_name": "Club / Organization Name",
    "quote.contact_person": "Contact Person",
    "quote.reference": "Reference",
    "quote.generating": "Generating...",
    "quote.download_button": "Download & Email Quote",
    "services.title": "Our Expertise & Services",
    "services.subtitle": "Professional timekeeping solutions and expert services.",
    "services.equipe_cta": "Explore Equipe Setup",
    "services.training_cta": "Explore Training Service",
    "services.equipe_desc_short": "Equestrian show management experts.",
    "services.training_desc_short": "Comprehensive field operations, training, and consultation.",
    "services.equipe_full": "As experts in equestrian events, we provide full integration, setup, and support for the Equipe software ecosystem. We connect your FDS Timing hardware directly to the digital scoreboard.",
    "services.training_full": "We provide deep, hands-on support for your events. Whether you are setting up a local club match or a massive international tournament, our field training ensures your staff is confident and your results are flawless.",
    "services.feature.on_site": "On-site staff training",
    "services.feature.setup": "Equipment setup & tear-down",
    "services.feature.live": "Live results management",
    "services.feature.bridge": "Software-hardware bridging",
    "services.feature.auto": "Automated timing inputs",
    "services.feature.config": "Custom show configurations",
    "equipe.title": "Equipe Software & Integration",
    "equipe.subtitle": "Equestrian Standard",
    "equipe.desc": "We are experts in equestrian show management. Eqilo provides full support for the world's leading competition management system.",
    "equipe.visit": "Visit Equipe.com",
    "equipe.live": "Live Results & Start Lists",
    "equipe.live_desc": "Seamless real-time visibility for your audience.",
    "equipe.feature1.title": "Hardware Integration",
    "equipe.feature1.desc": "Connect your FDS Timing devices directly to Equipe for automatic time updates.",
    "equipe.feature2.title": "Cloud Services",
    "equipe.feature2.desc": "Manage start lists, results, and live broadcasts as a centralized cloud service.",
    "equipe.feature3.title": "Show Customization",
    "equipe.feature3.desc": "Configure rules, classes, and show-specific settings for the Finnish market.",
    "equipe.cta_title": "Ready to Modernize Your Show?",
    "equipe.cta_desc": "We have helped dozens of clubs take the digital leap. Contact us and let's design the perfect package for your association.",
    "equipe.browse": "Browse Hardware",
    "search.placeholder": "Search equipment by name or SKU...",
    "search.no_results": "No equipment found matching your search.",
    "search.results": "Search Results",
    "search.suggested": "Suggested Equipment",
    "footer.company": "Company",
    "footer.store": "Store",
    "footer.partners": "Partners",
    "footer.terms": "Terms & Conditions",
    "footer.business_id": "Business ID",
    "footer.rights": "All rights reserved.",
    "footer.company_desc": "Modern timekeeping devices from Swiss manufacturer FDS Timing. Eqilo provides over 20 years of expertise to Finnish agility and equestrian clubs.",
    "cookie.title": "We value your privacy",
    "cookie.desc": "We use cookies to enhance your browsing experience, serve personalized content, and analyze our traffic.",
    "cookie.accept": "Accept All",
    "cookie.decline": "Decline Optional",
    "whatsapp.chat": "Chat on WhatsApp",
    "whatsapp.online": "Online",
    "whatsapp.welcome": "Hi! How can I help you with timekeeping equipment today?",
    "whatsapp.scan_title": "Scan to Chat",
    "whatsapp.scan_desc": "Scan with your phone to open WhatsApp.",
    "whatsapp.web_link": "Or click here for WhatsApp Web",
    "whatsapp.ask_johannes": "Ask Johannes",
  },
  SE: {
    "nav.products": "Produkter",
    "nav.services": "Tjänster",
    "nav.consulting": "Eqilo Konsulting",
    "nav.training": "Utbildning & Resultat",
    "nav.equipe": "Equipe Programvara",
    "nav.cart": "Kundvagn",
    "nav.admin": "Administratörsportal",
    "nav.login": "Logga In",
    "nav.logout": "Logga Ut",
    "nav.my_orders": "Mina Beställningar",
    "nav.profile": "Profil",
    "nav.terms": "Villkor",
    "nav.privacy": "Integritetspolicy",
    "nav.cookie": "Cookiepolicy",
    "nav.sports": "Sporter",
    "nav.contact_us": "Kontakta Oss",
    "nav.consulting_desc": "Över 20 års erfarenhet av tävlings- och tidtagningssystem.",
    "nav.training_desc": "Fältverksamhet och personalutbildning.",
    "nav.equipe_desc": "Standard för hantering av ridsportstävlingar.",
    "nav.search_sr": "Sök produkter",
    "nav.language": "Språk",
    "home.hero.title": "Moderna tidtagningslösningar för proffs",
    "home.hero.subtitle": "Eqilo.fi tar schweizisk FDS Timing-teknik till finska agility- och ridklubbar. Trådlöst, väderbeständigt och sömlöst integrerat.",
    "home.hero.shop": "Köp Utrustning",
    "home.hero.services": "Våra Tjänster",
    "home.partners.title": "Betrodd av & Officiell partner till",
    "home.advantages.title": "Fördelarna med FDS Timing",
    "home.advantages.subtitle": "Varför klubbar över hela Finland uppgraderar till modern FDS Timing-utrustning.",
    "home.advantage.wireless.title": "100% Trådlöst",
    "home.advantage.wireless.desc": "Lätt att använda och snabb att installera. Inga externa kablar krävs på fältet.",
    "home.advantage.battery.title": "Inbyggt batteri",
    "home.advantage.battery.desc": "Modern och kompakt teknik. Inga klumpiga externa batteripaket att hantera.",
    "home.advantage.software.title": "Programvarukompatibel",
    "home.advantage.software.desc": "Direkt integration med populära resultattjänster som Equipe.",
    "home.advantage.weather.title": "Väderbeständig",
    "home.advantage.weather.desc": "Robust konstruktion som säkerställer pålitlig prestanda i krävande miljöer.",
    "home.advantage.cost.title": "Kostnadseffektiv",
    "home.advantage.cost.desc": "Rimlig kostnad jämfört med äldre, tunga traditionella system.",
    "home.advantage.more.title": "Utforska mer",
    "home.advantage.more.desc": "Lämplig för alla tävlingsnivåer, från klubbtävlingar till internationella evenemang.",
    "home.advantage.more.button": "Sök i katalogen",
    "home.services.title": "20 års expertis",
    "home.services.desc": "Utöver försäljning av utrustning erbjuder vi tävlingskonsultation, teknisk support, utrustningsservice och dedikerad utbildning för tidtagningssystem.",
    "home.services.button": "Upptäck våra tjänster",
    "home.services.expert_cta": "Behöver du en expert till ditt evenemang?",
    "home.services.expert_desc": "Johannes Hyrsky och Eqilo-teamet är redo att hjälpa till.",
    "home.quote.text": "\"Vårt mål är att avsevärt förbättra tillgången till moderna tidtagningslösningar i Finland och sänka tröskeln för klubbar att använda professionell teknik.\"",
    "home.quote.author": "Johannes Hyrsky",
    "home.quote.role": "Butiksägare & Expert",
    "shop.all_equipment": "All Utrustning",
    "shop.categories": "Kategorier",
    "shop.view_details": "Visa Detaljer",
    "shop.items_found": "produkter hittades",
    "shop.in_stock": "I lager",
    "shop.add": "Lägg till",
    "shop.price": "Pris",
    "shop.description": "Professionella tidtagningslösningar för klubbar.",
    "shop.loading": "Laddar professionell utrustning...",
    "product.sku": "Artikelnr",
    "product.incl_vat": "inkl. moms",
    "product.standard_shipping": "Standardfrakt: 1-2 veckor",
    "product.shipping_details": "Produkter skickas direkt till Finland. Fri frakt på beställningar över 200 €.",
    "product.add_to_cart": "Lägg i varukorg",
    "product.description": "Beskrivning",
    "product.specs": "Specifikationer",
    "product.weight": "Vikt",
    "product.category": "Kategori",
    "product.box_contents": "Förpackningens innehåll",
    "product.downloads": "Nedladdningar & Manualer",
    "product.videos": "Instruktionsvideor",
    "product.guarantee": "Kvalitetsgaranti",
    "product.loading": "Laddar produktinformation...",
    "product.image_pending": "Produktbild kommer snart",
    "product.customize_kit": "Anpassa ditt paket",
    "product.quantity": "Antal",
    "product.guarantee_desc": "Alla FDS Timing-enheter backas upp av schweizisk ingenjörskonst och stöds lokalt av Eqilos 20 års expertis.",
    "category.after-sales": "Eftermarknad",
    "category.peripheral": "Kringutrustning",
    "category.display": "Displayer",
    "category.cables": "Kablar",
    "category.accessories": "Tillbehör",
    "category.ios-app": "iOS App",
    "category.kit": "Paket",
    "category.timer": "Tidtagning",
    "category.loading": "Laddar...",
    "category.empty": "Inga produkter hittades i denna kategori.",
    "category.description_prefix": "Professionella FDS Timing-lösningar för",
    "cart.title": "Kundvagn",
    "cart.empty": "Din kundvagn är tom",
    "cart.empty_sub": "Det ser ut som om du inte har lagt till någon FDS Timing-utrustning ännu.",
    "cart.browse": "Bläddra bland produkter",
    "cart.summary": "Beställningssammanfattning",
    "cart.subtotal": "Delsumma",
    "cart.shipping": "Frakt (Finland)",
    "cart.total": "Totalt",
    "cart.checkout": "Gå till kassan",
    "cart.request_quote": "Begär officiell offert (PDF)",
    "cart.remove": "Ta bort",
    "cart.updating": "Uppdaterar kundvagnen...",
    "cart.clear_all": "Rensa",
    "cart.items_in_cart": "produkter i kundvagnen",
    "cart.unit": "st",
    "cart.free": "Gratis",
    "cart.or": "ELLER",
    "checkout.title": "Kassa",
    "checkout.billing": "Faktureringsuppgifter",
    "checkout.place_order": "Slutför köp",
    "checkout.loading": "Förbereder kassan...",
    "checkout.b2b_note": "Krävs för B2B-fakturering och momsbehandling",
    "checkout.stripe_note": "Betalningar behandlas säkert via Stripe. Dina uppgifter är krypterade och lagras aldrig på våra servrar.",
    "checkout.terms_agree": "Jag godkänner köpvillkoren",
    "checkout.optional": "Valfri",
    "checkout.success_title": "Order bekräftad!",
    "checkout.success_desc": "Tack för ditt köp. Din beställning behandlas nu.",
    "checkout.order_ref": "Orderreferens",
    "checkout.status": "Status",
    "checkout.total_paid": "Totalt betalat",
    "checkout.email_sent": "Ett bekräftelsemeddelande har skickats till",
    "checkout.shipping_note": "Standardleverans för FDS Timing-utrustning är 1-2 veckor.",
    "checkout.continue_shopping": "Fortsätt handla",
    "checkout.explore_services": "Utforska våra tjänster",
    "checkout.login_required": "Logga in för att fortsätta till kassan.",
    "auth.email": "E-post",
    "auth.phone": "Telefonnummer",
    "auth.password": "Lösenord",
    "auth.login": "Logga In",
    "auth.register": "Registrera",
    "auth.verify": "Bekräfta kod",
    "auth.send_code": "Skicka kod",
    "auth.or": "ELLER",
    "auth.login_title": "Välkommen tillbaka",
    "auth.register_title": "Skapa konto",
    "auth.need_account": "Behöver du ett konto? Registrera",
    "auth.already_have_account": "Har du jo ett konto? Logga in",
    "auth.sms_code": "SMS-kod",
    "auth.login_desc": "Logga in för att hantera dina beställningar och sparade kundvagnar.",
    "auth.register_desc": "Gå med i Eqilo.fi för att hantera din professionella utrustning.",
    "auth.phone_note": "Inkludera landskod (t.ex. +358).",
    "auth.otp_label": "Verifieringskod",
    "auth.back": "Tillbaka",
    "orders.loading": "Laddar dina beställningar...",
    "orders.description": "Följ dina FDS Timing-leveranser.",
    "orders.empty": "Inga beställningar hittades",
    "orders.empty_sub": "Du har inte gjort några beställningar ännu.",
    "orders.id": "Ordernummer",
    "orders.date": "Datum",
    "orders.items": "Orderinnehåll",
    "orders.delivery_details": "Leveransuppgifter",
    "orders.tracking": "Leveransspårning",
    "orders.product_id": "Produktnummer",
    "orders.tax_breakdown": "Momspecifikation",
    "orders.track_button": "Spåra",
    "orders.paid": "Betald",
    "orders.processing": "Behandlas",
    "orders.shipped": "Skickad",
    "orders.delivered": "Levererad",
    "quote.title": "Begär officiell offert",
    "quote.desc": "Ange din organisations information. Vi skapar en officiell PDF-offert för styrelsens godkännande och skickar en kopia till din e-post.",
    "quote.org_name": "Klubb / Organisation",
    "quote.contact_person": "Kontaktperson",
    "quote.reference": "Referens",
    "quote.generating": "Genererar...",
    "quote.download_button": "Ladda ner och skicka offert",
    "services.title": "Vår Expertis & Tjänster",
    "services.subtitle": "Professionella tidtagningslösningar och experttjänster.",
    "services.equipe_cta": "Utforska Equipe-konfiguration",
    "services.training_cta": "Utforska utbildningstjänsten",
    "services.equipe_desc_short": "Experter på hantering av ridsportstävlingar.",
    "services.training_desc_short": "Omfattande fältoperationer, utbildning och konsultation.",
    "services.equipe_full": "Som experter på ridsportsevenemang erbjuder vi fullständig integration, installation och support för Equipe-programvarans ekosystem. Vi ansluter din FDS Timing-maskinvara direkt till den digitala resultattavlan.",
    "services.training_full": "Vi erbjuder djupgående, praktiskt stöd för dina evenemang. Oavsett om du förbereder en lokal klubbtävling eller en stor internationell turnering säkerställer vår fältutbildning att din personal är trygg och dina resultat felfria.",
    "services.feature.on_site": "Personalutbildning på plats",
    "services.feature.setup": "Utrustningens upp- och nedmontering",
    "services.feature.live": "Hantering av liveresultat",
    "services.feature.bridge": "Programvara-hårdvara brygga",
    "services.feature.auto": "Automatiserade tidtagningsinmatningar",
    "services.feature.config": "Anpassade tävlingskonfigurationer",
    "equipe.title": "Equipe Programvara & Integration",
    "equipe.subtitle": "Standard för ridsport",
    "equipe.desc": "Vi är experter på hantering av ridsportstävlingar. Eqilo erbjuder fullt stöd för världens ledande tävlingshanteringssystem.",
    "equipe.visit": "Besök Equipe.com",
    "equipe.live": "Liveresultat & Startlistor",
    "equipe.live_desc": "Sömlös realtidsvisning för din publik.",
    "equipe.feature1.title": "Hårdvaruintegration",
    "equipe.feature1.desc": "Anslut dina FDS Timing-enheter direkt till Equipe för automatiska tidsuppdateringar.",
    "equipe.feature2.title": "Molntjänster",
    "equipe.feature2.desc": "Hantera startlistor, resultat och livesändningar som en centraliserad molntjänst.",
    "equipe.feature3.title": "Tävlingsanpassning",
    "equipe.feature3.desc": "Konfigurera regler, klasser och tävlingsspecifika inställningar för den finska marknaden.",
    "equipe.cta_title": "Redo att modernisera din tävling?",
    "equipe.cta_desc": "Vi har hjälpt dussintals klubbar att ta det digitala språnget. Kontakta oss så designar vi det perfekta paketet för din förening.",
    "equipe.browse": "Sök i katalogen",
    "search.placeholder": "Sök efter utrustning...",
    "search.no_results": "Hittade ingen utrustning.",
    "search.results": "Sökresultat",
    "search.suggested": "Föreslagen utrustning",
    "footer.company": "Företag",
    "footer.store": "Butik",
    "footer.partners": "Partners",
    "footer.terms": "Villkor",
    "footer.business_id": "Org.nr",
    "footer.rights": "Med ensamrätt.",
    "footer.company_desc": "Modern tidtagningsutrustning från schweiziska FDS Timing. Eqilo erbjuder över 20 års expertis till finska agility- och ridklubbar.",
    "cookie.title": "Vi värnar om din integritet",
    "cookie.desc": "Vi använder cookies för att förbättra din webbupplevelse, visa personligt innehåll och analysera vår trafik.",
    "cookie.accept": "Acceptera alla",
    "cookie.decline": "Avvisa valfria",
    "whatsapp.chat": "Prata på WhatsApp",
    "whatsapp.online": "Online",
    "whatsapp.welcome": "Hej! Hur kan jag hjälpa dig med tidtagningsutrustning idag?",
    "whatsapp.scan_title": "Skanna och chatta",
    "whatsapp.scan_desc": "Skanna koden med din telefon för att öppna WhatsApp.",
    "whatsapp.web_link": "Eller klicka här för WhatsApp Web",
    "whatsapp.ask_johannes": "Fråga Johannes",
  }
};

interface LanguageContextType {
  lang: Language;
  setLang: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType>({
  lang: "FI",
  setLang: () => {},
  t: (key) => key,
});

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLang] = useState<Language>("FI");
  const [mounted, setMounted] = useState(false);

  useEffect(() => {
    const savedLang = localStorage.getItem("eqilo_lang") as Language;
    if (savedLang && ["FI", "EN", "SE"].includes(savedLang)) {
      // eslint-disable-next-line react-hooks/set-state-in-effect
      setLang(savedLang);
    }
    setMounted(true);
  }, []);

  useEffect(() => {
    if (mounted) {
      document.documentElement.lang = lang.toLowerCase();
    }
  }, [lang, mounted]);

  const handleSetLang = (newLang: Language) => {
    setLang(newLang);
    localStorage.setItem("eqilo_lang", newLang);
  };

  const t = (key: string) => {
    return dictionaries[lang][key] || dictionaries["EN"][key] || key;
  };

  if (!mounted) return <>{children}</>;

  return (
    <LanguageContext.Provider value={{ lang, setLang: handleSetLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export const useLanguage = () => useContext(LanguageContext);
