"use client";

import React, { createContext, useContext, useState, useEffect } from "react";

type Language = "FI" | "EN" | "SE";

interface TranslationDictionary {
  [key: string]: string;
}

const dictionaries: Record<Language, TranslationDictionary> = {
  FI: {
    "nav.products": "Tuotteet",
    "nav.services": "Palvelut",
    "nav.consulting": "Eqilo Konsultointi",
    "nav.training": "Koulutus & Tulospalvelu",
    "nav.equipe": "Equipe Ohjelmisto",
    "nav.cart": "Ostoskori",
    "nav.admin": "Hallintapaneeli",
    "nav.login": "Kirjaudu Sisään",
    "nav.logout": "Kirjaudu Ulos",
    "nav.my_orders": "Omat Tilaukset",
    "nav.profile": "Profiili",
    "nav.terms": "Käyttöehdot",
    "home.hero.title": "Modernit ajanottoratkaisut ammattilaisille",
    "home.hero.subtitle": "Eqilo.fi tuo sveitsiläisen FDS Timing -teknologian suomalaisiin agility- ja ratsastusseuroihin. Langaton, säänkestävä ja saumattomasti integroituva.",
    "home.hero.shop": "Osta Laitteita",
    "home.hero.services": "Palvelumme",
    "home.partners.title": "Yhteistyössä",
    "home.advantages.title": "FDS Timingin edut",
    "home.advantages.subtitle": "Miksi seurat ympäri Suomea valitsevat nykyaikaiset FDS Timing -laitteet.",
    "home.advantage.wireless.title": "100% Langaton",
    "home.advantage.wireless.desc": "Helppo käyttää ja nopea asentaa. Ei häiritseviä kaapeleita kentällä.",
    "home.advantage.battery.title": "Sisäänrakennettu akku",
    "home.advantage.battery.desc": "Moderni ja kompakti teknologia. Ei kömpelöitä ulkoisia akkuja.",
    "home.advantage.software.title": "Ohjelmistoyhteensopiva",
    "home.advantage.software.desc": "Suora integraatio suosittuihin tulospalveluihin, kuten Equipeen.",
    "home.advantage.weather.title": "Säänkestävä",
    "home.advantage.weather.desc": "Vankka rakenne takaa luotettavan toiminnan vaativissa olosuhteissa.",
    "home.advantage.cost.title": "Kustannustehokas",
    "home.advantage.cost.desc": "Kohtuullinen hinta verrattuna vanhoihin, raskaisiin perinteisiin järjestelmiin.",
    "home.advantage.more.title": "Lue lisää",
    "home.advantage.more.desc": "Sopii kaikille tasoille seurakilpailuista kansainvälisiin arvokisoihin.",
    "home.advantage.more.button": "Selaa tuotteita",
    "home.services.title": "20 vuoden asiantuntemus",
    "home.services.desc": "Laitteiden myynnin lisäksi tarjoamme kilpailukonsultointia, teknistä tukea, huoltoa ja dedikoitua koulutusta ajanottojärjestelmiin.",
    "home.services.button": "Tutustu palveluihimme",
    "home.quote.text": "\"Tavoitteemme on parantaa nykyaikaisten ajanottoratkaisujen saatavuutta Suomessa ja madaltaa seurojen kynnystä ammattiteknologian käyttöön.\"",
    "home.quote.author": "Johannes Hyrsky",
    "home.quote.role": "Kauppias & Asiantuntija",
    "shop.all_equipment": "Kaikki Laitteet",
    "shop.categories": "Kategoriat",
    "shop.view_details": "Katso Tiedot",
    "shop.items_found": "tuotetta löytyi",
    "shop.in_stock": "Varastossa",
    "shop.add": "Lisää",
    "product.sku": "Tuotekoodi",
    "product.incl_vat": "sis. alv",
    "product.standard_shipping": "Vakiotoimitus: 1-2 viikkoa",
    "product.shipping_details": "Tuotteet toimitetaan suoraan Suomeen. Ilmainen toimitus yli 200 € tilauksiin.",
    "product.add_to_cart": "Lisää ostoskoriin",
    "product.description": "Kuvaus",
    "product.specs": "Tekniset tiedot",
    "product.weight": "Paino",
    "product.category": "Kategoria",
    "product.box_contents": "Pakkauksen sisältö",
    "product.downloads": "Lataukset",
    "product.guarantee": "Laatutakuu",
    "category.after-sales": "Huoltopalvelut",
    "category.peripheral": "Oheislaitteet",
    "category.display": "Näytöt",
    "category.cables": "Kaapelit",
    "category.accessories": "Tarvikkeet",
    "category.ios-app": "iOS-sovellus",
    "category.kit": "Tuotepaketit",
    "category.timer": "Ajanottolaitteet",
    "cart.title": "Ostoskori",
    "cart.empty": "Ostoskorisi on tyhjä",
    "cart.empty_sub": "Et ole vielä lisännyt FDS Timing -laitteita ostoskoriisi.",
    "cart.browse": "Selaa tuotteita",
    "cart.summary": "Tilausyhteenveto",
    "cart.subtotal": "Välisumma",
    "cart.shipping": "Toimitus (Suomi)",
    "cart.total": "Yhteensä",
    "cart.checkout": "Siirry kassalle",
    "cart.request_quote": "Lataa virallinen tarjous (PDF)",
    "cart.remove": "Poista",
    "checkout.title": "Kassa",
    "checkout.billing": "Laskutustiedot",
    "checkout.place_order": "Maksa tilaus",
    "auth.email": "Sähköposti",
    "auth.phone": "Puhelinnumero",
    "auth.password": "Salasana",
    "auth.login": "Kirjaudu",
    "auth.register": "Rekisteröidy",
    "auth.verify": "Vahvista koodi",
    "auth.send_code": "Lähetä koodi",
    "auth.or": "TAI",
    "auth.login_title": "Tervetuloa takaisin",
    "auth.register_title": "Luo tili",
    "auth.need_account": "Tarvitsetko tilin? Rekisteröidy",
    "auth.already_have_account": "Onko sinulla jo tili? Kirjaudu",
    "auth.sms_code": "Tekstiviestikoodi",
    "search.placeholder": "Etsi tuotteita nimellä tai koodilla...",
    "search.no_results": "Tuotteita ei löytynyt.",
    "search.results": "Hakutulokset",
    "search.suggested": "Suositellut tuotteet",
    "footer.company": "Yritys",
    "footer.store": "Kauppa",
    "footer.partners": "Kumppanit",
    "footer.terms": "Käyttöehdot",
    "footer.business_id": "Y-Tunnus",
    "footer.rights": "Kaikki oikeudet pidätetään.",
    "footer.company_desc": "Modernit ajanottolaitteet sveitsiläiseltä FDS Timingilta. Eqilo tarjoaa yli 20 vuoden asiantuntemusta suomalaisille agility- ja ratsastusseuroille.",
    "cookie.title": "Yksityisyytesi on meille tärkeää",
    "cookie.desc": "Käytämme evästeitä parantaaksemme sivuston käyttökokemusta, tarjotaksemme kohdennettua sisältöä ja analysoidaksemme liikennettä.",
    "cookie.accept": "Hyväksy kaikki",
    "cookie.decline": "Vain välttämättömät",
    "whatsapp.chat": "Keskustele WhatsAppissa",
  },
  EN: {
    "nav.products": "Products",
    "nav.services": "Services",
    "nav.consulting": "Eqilo Consulting",
    "nav.training": "Training & Results",
    "nav.equipe": "Equipe Software",
    "nav.cart": "Cart",
    "nav.admin": "Admin Portal",
    "nav.login": "Sign In",
    "nav.logout": "Sign Out",
    "nav.my_orders": "My Orders",
    "nav.profile": "Profile",
    "nav.terms": "Terms & Conditions",
    "home.hero.title": "Modern Timekeeping Solutions for Professionals",
    "home.hero.subtitle": "Eqilo.fi brings Swiss-engineered FDS Timing technology to Finnish agility and equestrian clubs. Wireless, weatherproof, and seamlessly integrated.",
    "home.hero.shop": "Shop Equipment",
    "home.hero.services": "Our Services",
    "home.partners.title": "Trusted By & Official Partner Of",
    "home.advantages.title": "The FDS Timing Advantage",
    "home.advantages.subtitle": "Why clubs across Finland are upgrading to modern FDS Timing equipment.",
    "home.advantage.wireless.title": "100% Wireless",
    "home.advantage.wireless.desc": "Easy to use and quick to deploy. No external cables required on the field.",
    "home.advantage.battery.title": "Built-in Battery",
    "home.advantage.battery.desc": "Modern and compact technology. No clunky external battery packs to manage.",
    "home.advantage.software.title": "Software Compatible",
    "home.advantage.software.desc": "Direct integration with popular results services like Equipe and SmarterAgility.",
    "home.advantage.weather.title": "Weatherproof",
    "home.advantage.weather.desc": "Robust construction ensuring reliable performance in demanding environments.",
    "home.advantage.cost.title": "Cost-Effective",
    "home.advantage.cost.desc": "Reasonable cost compared to legacy, heavy traditional systems.",
    "home.advantage.more.title": "Explore More",
    "home.advantage.more.desc": "Suitable for all event levels from club competitions to international events.",
    "home.advantage.more.button": "Browse Catalog",
    "home.services.title": "20 Years of Expertise",
    "home.services.desc": "Beyond equipment sales, we provide competition consultation, technical support, equipment service, and dedicated training for timekeeping and results systems.",
    "home.services.button": "Discover Our Services",
    "home.quote.text": "\"Our goal is to significantly improve accessibility to modern timekeeping solutions in Finland, lowering the barrier for clubs to adopt professional-level technology.\"",
    "home.quote.author": "Johannes Hyrsky",
    "home.quote.role": "Store Owner & Expert",
    "shop.all_equipment": "All Equipment",
    "shop.categories": "Categories",
    "shop.view_details": "View Details",
    "shop.items_found": "items found",
    "shop.in_stock": "In Stock",
    "shop.add": "Add",
    "product.sku": "SKU",
    "product.incl_vat": "incl. VAT",
    "product.standard_shipping": "Standard Shipping: 1-2 Weeks",
    "product.shipping_details": "Products are shipped directly to Finland. Free shipping on orders over 200 €.",
    "product.add_to_cart": "Add to Cart",
    "product.description": "Description",
    "product.specs": "Specifications",
    "product.weight": "Weight",
    "product.category": "Category",
    "product.box_contents": "Box Contents",
    "product.downloads": "Downloads",
    "product.guarantee": "Quality Guarantee",
    "category.after-sales": "After-Sales",
    "category.peripheral": "Peripherals",
    "category.display": "Displays",
    "category.cables": "Cables",
    "category.accessories": "Accessories",
    "category.ios-app": "iOS App",
    "category.kit": "Kits",
    "category.timer": "Timers",
    "cart.title": "Shopping Cart",
    "cart.empty": "Your cart is empty",
    "cart.empty_sub": "Looks like you haven't added any FDS Timing equipment to your cart yet.",
    "cart.browse": "Browse Products",
    "cart.summary": "Order Summary",
    "cart.subtotal": "Subtotal",
    "cart.shipping": "Shipping (Finland)",
    "cart.total": "Total",
    "cart.checkout": "Proceed to Checkout",
    "cart.request_quote": "Request Official Quote (PDF)",
    "cart.remove": "Remove",
    "checkout.title": "Checkout",
    "checkout.billing": "Billing Details",
    "checkout.place_order": "Place Order",
    "auth.email": "Email",
    "auth.phone": "Phone Number",
    "auth.password": "Password",
    "auth.login": "Log in",
    "auth.register": "Register",
    "auth.verify": "Verify Code",
    "auth.send_code": "Send Code",
    "auth.or": "OR",
    "auth.login_title": "Welcome Back",
    "auth.register_title": "Create Account",
    "auth.need_account": "Need an account? Register",
    "auth.already_have_account": "Already have an account? Log in",
    "auth.sms_code": "SMS Code",
    "search.placeholder": "Search equipment by name or SKU...",
    "search.no_results": "No equipment found matching your search.",
    "search.results": "Search Results",
    "search.suggested": "Suggested Equipment",
    "footer.company": "Company",
    "footer.store": "Store",
    "footer.partners": "Partners",
    "footer.terms": "Terms & Conditions",
    "footer.business_id": "Business ID",
    "footer.rights": "All rights reserved.",
    "footer.company_desc": "Modern timekeeping devices from Swiss manufacturer FDS Timing. Eqilo provides over 20 years of expertise to Finnish agility and equestrian clubs.",
    "cookie.title": "We value your privacy",
    "cookie.desc": "We use cookies to enhance your browsing experience, serve personalized content, and analyze our traffic.",
    "cookie.accept": "Accept All",
    "cookie.decline": "Decline Optional",
    "whatsapp.chat": "Chat on WhatsApp",
  },
  SE: {
    "nav.products": "Produkter",
    "nav.services": "Tjänster",
    "nav.consulting": "Eqilo Konsulting",
    "nav.training": "Utbildning & Resultat",
    "nav.equipe": "Equipe Programvara",
    "nav.cart": "Kundvagn",
    "nav.admin": "Administratörsportal",
    "nav.login": "Logga In",
    "nav.logout": "Logga Ut",
    "nav.my_orders": "Mina Beställningar",
    "nav.profile": "Profil",
    "nav.terms": "Villkor",
    "home.hero.title": "Moderna tidtagningslösningar för proffs",
    "home.hero.subtitle": "Eqilo.fi tar schweizisk FDS Timing-teknik till finska agility- och ridklubbar. Trådlöst, väderbeständigt och sömlöst integrerat.",
    "home.hero.shop": "Köp Utrustning",
    "home.hero.services": "Våra Tjänster",
    "home.partners.title": "Betrodd av & Officiell partner till",
    "home.advantages.title": "Fördelarna med FDS Timing",
    "home.advantages.subtitle": "Varför klubbar över hela Finland uppgraderar till modern FDS Timing-utrustning.",
    "home.advantage.wireless.title": "100% Trådlöst",
    "home.advantage.wireless.desc": "Lätt att använda och snabb att installera. Inga externa kablar krävs på fältet.",
    "home.advantage.battery.title": "Inbyggt batteri",
    "home.advantage.battery.desc": "Modern och kompakt teknik. Inga klumpiga externa batteripaket att hantera.",
    "home.advantage.software.title": "Programvarukompatibel",
    "home.advantage.software.desc": "Direkt integration med populära resultattjänster som Equipe.",
    "home.advantage.weather.title": "Väderbeständig",
    "home.advantage.weather.desc": "Robust konstruktion som säkerställer pålitlig prestanda i krävande miljöer.",
    "home.advantage.cost.title": "Kostnadseffektiv",
    "home.advantage.cost.desc": "Rimlig kostnad jämfört med äldre, tunga traditionella system.",
    "home.advantage.more.title": "Utforska mer",
    "home.advantage.more.desc": "Lämplig för alla tävlingsnivåer, från klubbtävlingar till internationella evenemang.",
    "home.advantage.more.button": "Sök i katalogen",
    "home.services.title": "20 års expertis",
    "home.services.desc": "Utöver försäljning av utrustning erbjuder vi tävlingskonsultation, teknisk support, utrustningsservice och dedikerad utbildning för tidtagningssystem.",
    "home.services.button": "Upptäck våra tjänster",
    "home.quote.text": "\"Vårt mål är att avsevärt förbättra tillgången till moderna tidtagningslösningar i Finland och sänka tröskeln för klubbar att använda professionell teknik.\"",
    "home.quote.author": "Johannes Hyrsky",
    "home.quote.role": "Butiksägare & Expert",
    "shop.all_equipment": "All Utrustning",
    "shop.categories": "Kategorier",
    "shop.view_details": "Visa Detaljer",
    "shop.items_found": "produkter hittades",
    "shop.in_stock": "I lager",
    "shop.add": "Lägg till",
    "product.sku": "Artikelnr",
    "product.incl_vat": "inkl. moms",
    "product.standard_shipping": "Standardfrakt: 1-2 veckor",
    "product.shipping_details": "Produkter skickas direkt till Finland. Fri frakt på beställningar över 200 €.",
    "product.add_to_cart": "Lägg i varukorg",
    "product.description": "Beskrivning",
    "product.specs": "Specifikationer",
    "product.weight": "Vikt",
    "product.category": "Kategori",
    "product.box_contents": "Förpackningens innehåll",
    "product.downloads": "Nedladdningar",
    "product.guarantee": "Kvalitetsgaranti",
    "category.after-sales": "Eftermarknad",
    "category.peripheral": "Kringutrustning",
    "category.display": "Displayer",
    "category.cables": "Kablar",
    "category.accessories": "Tillbehör",
    "category.ios-app": "iOS App",
    "category.kit": "Paket",
    "category.timer": "Tidtagning",
    "cart.title": "Kundvagn",
    "cart.empty": "Din kundvagn är tom",
    "cart.empty_sub": "Det ser ut som om du inte har lagt till någon FDS Timing-utrustning ännu.",
    "cart.browse": "Bläddra bland produkter",
    "cart.summary": "Beställningssammanfattning",
    "cart.subtotal": "Delsumma",
    "cart.shipping": "Frakt (Finland)",
    "cart.total": "Totalt",
    "cart.checkout": "Gå till kassan",
    "cart.request_quote": "Begär officiell offert (PDF)",
    "cart.remove": "Ta bort",
    "checkout.title": "Kassa",
    "checkout.billing": "Faktureringsuppgifter",
    "checkout.place_order": "Slutför köp",
    "auth.email": "E-post",
    "auth.phone": "Telefonnummer",
    "auth.password": "Lösenord",
    "auth.login": "Logga In",
    "auth.register": "Registrera",
    "auth.verify": "Bekräfta kod",
    "auth.send_code": "Skicka kod",
    "auth.or": "ELLER",
    "auth.login_title": "Välkommen tillbaka",
    "auth.register_title": "Skapa konto",
    "auth.need_account": "Behöver du ett konto? Registrera",
    "auth.already_have_account": "Har du jo ett konto? Logga in",
    "auth.sms_code": "SMS-kod",
    "search.placeholder": "Sök efter utrustning...",
    "search.no_results": "Hittade ingen utrustning.",
    "search.results": "Sökresultat",
    "search.suggested": "Föreslagen utrustning",
    "footer.company": "Företag",
    "footer.store": "Butik",
    "footer.partners": "Partners",
    "footer.terms": "Villkor",
    "footer.business_id": "Org.nr",
    "footer.rights": "Med ensamrätt.",
    "footer.company_desc": "Modern tidtagningsutrustning från schweiziska FDS Timing. Eqilo erbjuder över 20 års expertis till finska agility- och ridklubbar.",
    "cookie.title": "Vi värnar om din integritet",
    "cookie.desc": "Vi använder cookies för att förbättra din webbupplevelse, visa personligt innehåll och analysera vår trafik.",
    "cookie.accept": "Acceptera alla",
    "cookie.decline": "Avvisa valfria",
    "whatsapp.chat": "Prata på WhatsApp",
  }
};

interface LanguageContextType {
  lang: Language;
  setLang: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType>({
  lang: "FI",
  setLang: () => {},
  t: (key) => key,
});

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLang] = useState<Language>("FI");
  const [mounted, setMounted] = useState(false);

  useEffect(() => {
    const savedLang = localStorage.getItem("eqilo_lang") as Language;
    if (savedLang && ["FI", "EN", "SE"].includes(savedLang)) {
      setLang(savedLang);
    }
    setMounted(true);
  }, []);

  const handleSetLang = (newLang: Language) => {
    setLang(newLang);
    localStorage.setItem("eqilo_lang", newLang);
  };

  const t = (key: string) => {
    return dictionaries[lang][key] || dictionaries["EN"][key] || key;
  };

  if (!mounted) return <>{children}</>;

  return (
    <LanguageContext.Provider value={{ lang, setLang: handleSetLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export const useLanguage = () => useContext(LanguageContext);
